### PR TITLE
feat(logging): implemented rTracer for request ID Tracking

### PR DESCRIPTION
**Pull request by ihatelactose**
### Description

Implemented rTracer to log request received and response sent back to the client.
Request ID is generated for each request and is also placed into the headers as `x-request-id` for each response sent out.

### Steps to Reproduce / Test

Tests can be ran using:
```
yarn test
```

### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added]
- [ ] Relevant documentation is changed or added (and PR referenced)

### CODE REVIEW

**Comment by praveenkumar1798** [comment]
is the sequelize logging handled to support this ?

**Review by alichherawalla — APPROVED** [review]
🙌

**Review by christin-wednesday — COMMENTED** [review]
We should keep sql logs.

**Comment by praveenkumar1798** [comment]
> We should keep sql logs.

We are keeping sql logs. Just added the logger support to it and triggering it based on environments

**Review by christin-wednesday — APPROVED** [review]

**Pull request merged**
